require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EscrowsController do

  # This should return the minimal set of attributes required to create a valid
  # Escrow. As you add validations to Escrow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EscrowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all escrows as @escrows" do
      escrow = Escrow.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:escrows)).to eq([escrow])
    end
  end

  describe "GET show" do
    it "assigns the requested escrow as @escrow" do
      escrow = Escrow.create! valid_attributes
      get :show, {:id => escrow.to_param}, valid_session
      expect(assigns(:escrow)).to eq(escrow)
    end
  end

  describe "GET new" do
    it "assigns a new escrow as @escrow" do
      get :new, {}, valid_session
      expect(assigns(:escrow)).to be_a_new(Escrow)
    end
  end

  describe "GET edit" do
    it "assigns the requested escrow as @escrow" do
      escrow = Escrow.create! valid_attributes
      get :edit, {:id => escrow.to_param}, valid_session
      expect(assigns(:escrow)).to eq(escrow)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Escrow" do
        expect {
          post :create, {:escrow => valid_attributes}, valid_session
        }.to change(Escrow, :count).by(1)
      end

      it "assigns a newly created escrow as @escrow" do
        post :create, {:escrow => valid_attributes}, valid_session
        expect(assigns(:escrow)).to be_a(Escrow)
        expect(assigns(:escrow)).to be_persisted
      end

      it "redirects to the created escrow" do
        post :create, {:escrow => valid_attributes}, valid_session
        expect(response).to redirect_to(Escrow.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved escrow as @escrow" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Escrow).to receive(:save).and_return(false)
        post :create, {:escrow => { "user" => "invalid value" }}, valid_session
        expect(assigns(:escrow)).to be_a_new(Escrow)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Escrow).to receive(:save).and_return(false)
        post :create, {:escrow => { "user" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested escrow" do
        escrow = Escrow.create! valid_attributes
        # Assuming there are no other escrows in the database, this
        # specifies that the Escrow created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Escrow).to receive(:update).with({ "user" => "" })
        put :update, {:id => escrow.to_param, :escrow => { "user" => "" }}, valid_session
      end

      it "assigns the requested escrow as @escrow" do
        escrow = Escrow.create! valid_attributes
        put :update, {:id => escrow.to_param, :escrow => valid_attributes}, valid_session
        expect(assigns(:escrow)).to eq(escrow)
      end

      it "redirects to the escrow" do
        escrow = Escrow.create! valid_attributes
        put :update, {:id => escrow.to_param, :escrow => valid_attributes}, valid_session
        expect(response).to redirect_to(escrow)
      end
    end

    describe "with invalid params" do
      it "assigns the escrow as @escrow" do
        escrow = Escrow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Escrow).to receive(:save).and_return(false)
        put :update, {:id => escrow.to_param, :escrow => { "user" => "invalid value" }}, valid_session
        expect(assigns(:escrow)).to eq(escrow)
      end

      it "re-renders the 'edit' template" do
        escrow = Escrow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Escrow).to receive(:save).and_return(false)
        put :update, {:id => escrow.to_param, :escrow => { "user" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested escrow" do
      escrow = Escrow.create! valid_attributes
      expect {
        delete :destroy, {:id => escrow.to_param}, valid_session
      }.to change(Escrow, :count).by(-1)
    end

    it "redirects to the escrows list" do
      escrow = Escrow.create! valid_attributes
      delete :destroy, {:id => escrow.to_param}, valid_session
      expect(response).to redirect_to(escrows_url)
    end
  end

end
